import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React, { useState } from "react";
import { makeStyles } from "@material-ui/core/styles";
import Table from "@material-ui/core/Table";
import TableBody from "@material-ui/core/TableBody";
import TableCell from "@material-ui/core/TableCell";
import TableContainer from "@material-ui/core/TableContainer";
import TableHead from "@material-ui/core/TableHead";
import TableRow from "@material-ui/core/TableRow";
import Paper from "@material-ui/core/Paper";
import SearchBar from "material-ui-search-bar";
import Image from "next/image";
import Mercedes1 from '../public/car/1.jpeg'
import Mercedes2 from '../public/car/2.jpeg'
import Mercedes3 from '../public/car/3.jpeg'
import Mercedes4 from '../public/car/4.jpg'
import Mercedes5 from '../public/car/5.webp'
import Mercedes6 from '../public/car/6.webp'
import Mercedes7 from '../public/car/7.webp'
import Mercedes8 from '../public/car/8.webp'
import Mercedes9 from '../public/car/9.webp'
import Mercedes10 from '../public/car/10.webp'
import Mercedes11 from '../public/car/11.webp'
import Mercedes12 from '../public/car/12.webp'
import Mercedes13 from '../public/car/13.webp'
import Mercedes14 from '../public/car/14.webp'
import Mercedes15 from '../public/car/15.webp'
import Mercedes16 from '../public/car/16.webp'

interface food {
  name: string;
  type: string;
  fat: number;
  carbs: number;
  protein: number;
}

const useStyles = makeStyles({
  table: {
    minWidth: 650
  }
});

const originalRows: food[] = [
  { name: "CarWale Mercedes-Benz Cars Price in India - Mercedes-Benz Models 2023 - Reviews, Specs & Dealers - CarWale", type: 'Mercedes', img: Mercedes1 },
  { name: "Pexels Mercedes Benz Photos, Download Free Mercedes Benz", type: 'Mercedes', img: Mercedes2 },
  { name: "CarWale Mercedes-Benz Cars Price in India - Mercedes-Benz Models 2023 - Reviews, Specs & Dealers", type: 'Mercedes', img: Mercedes3 },
  { name: "Autocar India Mercedes-Benz Car Price, Images, Reviews and Specs | Autocar India", type: 'Mercedes', img: Mercedes4 },
  { name: "X1 Sports Activity Vehicle", type: 'bmw', img: Mercedes5 },
  { name: "X3 M Sports Activity Vehicle", type: 'bmw', img: Mercedes6 },
  { name: "X4 Sports Activity Coupe", type: 'bmw', img: Mercedes7 },
  { name: "X4 M Sports Activity Coupe", type: 'bmw', img: Mercedes8 },
  { name: "X5 Sports Activity Vehicle", type: 'bmw', img: Mercedes9 },
  { name: "X5 M Sports Activity Vehicle", type: 'bmw', img: Mercedes10 },
  { name: "X6 Sports Activity Coupe", type: 'bmw', img: Mercedes11 },
  { name: "2020–23 Corolla", type: 'Corolla', img: Mercedes12 },
  { name: "2014–19 Corolla", type: 'Corolla', img: Mercedes13 },
  { name: "2009–13 Corolla", type: 'Corolla', img: Mercedes14 },
  { name: "2004–08 Corolla", type: 'Corolla', img: Mercedes15 },
  { name: "1992–2003 Corolla", type: 'Corolla', img: Mercedes16 },
];

export default function Home() {
  const [rows, setRows] = useState<food[]>(originalRows);
  const [searched, setSearched] = useState<string>("");
  const classes = useStyles();

  const requestSearch = (searchedVal: string) => {
    const filteredRows = originalRows.filter((row) => {
      return row.type.toLowerCase().includes(searchedVal.toLowerCase());
    });
    setRows(filteredRows);
  };

  const cancelSearch = () => {
    setSearched("");
    requestSearch(searched);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.mainContent}>
        <Paper className={styles.content}>
        <SearchBar
          value={searched}
          onChange={(searchVal) => requestSearch(searchVal)}
          onCancelSearch={() => cancelSearch()}
        />
        <TableContainer>
          <Table className={classes.table} aria-label="simple table">
            <TableHead>
              <TableRow>
                <TableCell>Image</TableCell>
                <TableCell align="right">Name</TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              {rows.map((row) => (
                <TableRow key={row.name}>
                  <TableCell component="th" scope="row">
                    <Image width={200}  src={row.img} />
                  </TableCell>
                  <TableCell align="right">
                    {row.name}
                  </TableCell>
                  
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </TableContainer>
      </Paper>
    </div>
      </main>
      </>
  )
}
